#[profile.release]
#debug = true

[workspace]
members = [
    "waterpouring-rec",
    "waterpouring-rec2",
    "waterpouring-imp",
    "waterpouring-model",
    "waterpouring-talk",
    "waterpouring-bench",
    "waterpouring-wasm",
]
